#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace basinc_arayuz
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Yer_Istasyonu")]
	public partial class YerIstasyonuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRocketData(RocketData instance);
    partial void UpdateRocketData(RocketData instance);
    partial void DeleteRocketData(RocketData instance);
    #endregion
		
		public YerIstasyonuDataContext() : 
				base(global::basinc_arayuz.Properties.Settings.Default.Yer_IstasyonuConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public YerIstasyonuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YerIstasyonuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YerIstasyonuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YerIstasyonuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<RocketData> RocketDatas
		{
			get
			{
				return this.GetTable<RocketData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _Password;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RocketData")]
	public partial class RocketData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Irtifa;
		
		private string _IvmeX;
		
		private string _IvmeY;
		
		private string _IvmeZ;
		
		private string _GyroX;
		
		private string _GyroY;
		
		private string _GyroZ;
		
		private string _Sicaklik;
		
		private string _Aci;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIrtifaChanging(string value);
    partial void OnIrtifaChanged();
    partial void OnIvmeXChanging(string value);
    partial void OnIvmeXChanged();
    partial void OnIvmeYChanging(string value);
    partial void OnIvmeYChanged();
    partial void OnIvmeZChanging(string value);
    partial void OnIvmeZChanged();
    partial void OnGyroXChanging(string value);
    partial void OnGyroXChanged();
    partial void OnGyroYChanging(string value);
    partial void OnGyroYChanged();
    partial void OnGyroZChanging(string value);
    partial void OnGyroZChanged();
    partial void OnSicaklikChanging(string value);
    partial void OnSicaklikChanged();
    partial void OnAciChanging(string value);
    partial void OnAciChanged();
    #endregion
		
		public RocketData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Irtifa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Irtifa
		{
			get
			{
				return this._Irtifa;
			}
			set
			{
				if ((this._Irtifa != value))
				{
					this.OnIrtifaChanging(value);
					this.SendPropertyChanging();
					this._Irtifa = value;
					this.SendPropertyChanged("Irtifa");
					this.OnIrtifaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IvmeX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IvmeX
		{
			get
			{
				return this._IvmeX;
			}
			set
			{
				if ((this._IvmeX != value))
				{
					this.OnIvmeXChanging(value);
					this.SendPropertyChanging();
					this._IvmeX = value;
					this.SendPropertyChanged("IvmeX");
					this.OnIvmeXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IvmeY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IvmeY
		{
			get
			{
				return this._IvmeY;
			}
			set
			{
				if ((this._IvmeY != value))
				{
					this.OnIvmeYChanging(value);
					this.SendPropertyChanging();
					this._IvmeY = value;
					this.SendPropertyChanged("IvmeY");
					this.OnIvmeYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IvmeZ", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string IvmeZ
		{
			get
			{
				return this._IvmeZ;
			}
			set
			{
				if ((this._IvmeZ != value))
				{
					this.OnIvmeZChanging(value);
					this.SendPropertyChanging();
					this._IvmeZ = value;
					this.SendPropertyChanged("IvmeZ");
					this.OnIvmeZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GyroX", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GyroX
		{
			get
			{
				return this._GyroX;
			}
			set
			{
				if ((this._GyroX != value))
				{
					this.OnGyroXChanging(value);
					this.SendPropertyChanging();
					this._GyroX = value;
					this.SendPropertyChanged("GyroX");
					this.OnGyroXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GyroY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GyroY
		{
			get
			{
				return this._GyroY;
			}
			set
			{
				if ((this._GyroY != value))
				{
					this.OnGyroYChanging(value);
					this.SendPropertyChanging();
					this._GyroY = value;
					this.SendPropertyChanged("GyroY");
					this.OnGyroYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GyroZ", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GyroZ
		{
			get
			{
				return this._GyroZ;
			}
			set
			{
				if ((this._GyroZ != value))
				{
					this.OnGyroZChanging(value);
					this.SendPropertyChanging();
					this._GyroZ = value;
					this.SendPropertyChanged("GyroZ");
					this.OnGyroZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sicaklik", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sicaklik
		{
			get
			{
				return this._Sicaklik;
			}
			set
			{
				if ((this._Sicaklik != value))
				{
					this.OnSicaklikChanging(value);
					this.SendPropertyChanging();
					this._Sicaklik = value;
					this.SendPropertyChanged("Sicaklik");
					this.OnSicaklikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aci", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Aci
		{
			get
			{
				return this._Aci;
			}
			set
			{
				if ((this._Aci != value))
				{
					this.OnAciChanging(value);
					this.SendPropertyChanging();
					this._Aci = value;
					this.SendPropertyChanged("Aci");
					this.OnAciChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
